#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

# Check jenkins-cli exists and is executable
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic "[ ! -f /usr/bin/jenkins-cli ] && exit 1 || echo 'Jenkins-cli exists'"

# Check jpi and jenkins-jobs installed
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic "echo '[jenkins] 
user=admin
password=password
url=https://example-jenkins.com
query_plugins_info=False' > ~/config.ini && jpi restart --conf ~/config.ini"
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'jenkins-jobs --version'

echo "SUCCESS!"