--- 
apiVersion: v1
kind: Template
labels: 
  template: jenkins-wendy-slaves-template
message: "A Jenkins service has been created in your project.  The username/password are admin/${JENKINS_PASSWORD}.  The tutorial at https://github.com/openshift/origin/blob/master/examples/jenkins/README.md contains more information about using this template."
metadata: 
  annotations: 
    description: |-
        Jenkins service, with persistent storage.
        You must have persistent volumes available in your cluster to use this template.
    iconClass: icon-jenkins
    tags: "instant-app,jenkins"
  name: jenkins-wendy-slaves
objects: 
  - 
    apiVersion: v1
    kind: ImageStream
    metadata: 
      annotations: 
        slave-label: nodejs-ubuntu
      labels: 
        role: jenkins-slave
      name: "${JENKINS_SERVICE_NAME}-slave-nodejs-ubuntu"
  - 
    apiVersion: v1
    kind: BuildConfig
    metadata: 
      name: "${JENKINS_SERVICE_NAME}-slave-nodejs-ubuntu"
    spec: 
      output: 
        to: 
          kind: ImageStreamTag
          name: "${JENKINS_SERVICE_NAME}-slave-nodejs-ubuntu:latest"
      runPolicy: Serial
      source: 
        contextDir: slave-nodejs-ubuntu
        git: 
          ref: "${GITHUB_REF}"
          uri: "https://github.com/${GITHUB_ORG}/wendy-jenkins-s2i-configuration"
        type: Git
      strategy: 
        dockerStrategy: 
          noCache: true
        type: Docker
      triggers: 
        - 
          type: ImageChange
        - 
          type: ConfigChange
  - 
    apiVersion: v1
    kind: ImageStream
    metadata: 
      annotations: 
        slave-label: java-ubuntu
      labels: 
        role: jenkins-slave
      name: "${JENKINS_SERVICE_NAME}-slave-java-ubuntu"
  - 
    apiVersion: v1
    kind: BuildConfig
    metadata: 
      name: "${JENKINS_SERVICE_NAME}-slave-java-ubuntu"
    spec: 
      output: 
        to: 
          kind: ImageStreamTag
          name: "${JENKINS_SERVICE_NAME}-slave-java-ubuntu:latest"
      runPolicy: Serial
      source: 
        contextDir: slave-java-ubuntu
        git: 
          ref: "${GITHUB_REF}"
          uri: "https://github.com/${GITHUB_ORG}/wendy-jenkins-s2i-configuration"
        type: Git
      strategy: 
        dockerStrategy: 
          noCache: true
        type: Docker
      triggers: 
        - 
          type: ImageChange
        - 
          type: ConfigChange
  - 
    apiVersion: v1
    kind: ImageStream
    metadata: 
      annotations: 
        slave-label: java
      labels: 
        role: jenkins-slave
      name: "${JENKINS_SERVICE_NAME}-slave-java"
  - 
    apiVersion: v1
    kind: BuildConfig
    metadata: 
      name: "${JENKINS_SERVICE_NAME}-slave-java"
    spec: 
      output: 
        to: 
          kind: ImageStreamTag
          name: "${JENKINS_SERVICE_NAME}-slave-java:latest"
      runPolicy: Serial
      source: 
        contextDir: slave-java
        git: 
          ref: "${GITHUB_REF}"
          uri: "https://github.com/${GITHUB_ORG}/wendy-jenkins-s2i-configuration"
        type: Git
      strategy: 
        dockerStrategy: 
          noCache: true
        type: Docker
      triggers: 
        - 
          type: ImageChange
        - 
          type: ConfigChange
  - 
    apiVersion: v1
    kind: ImageStream
    metadata: 
      annotations: 
        slave-label: ruby
      labels: 
        role: jenkins-slave
      name: "${JENKINS_SERVICE_NAME}-slave-ruby"
  - 
    apiVersion: v1
    kind: BuildConfig
    metadata: 
      name: "${JENKINS_SERVICE_NAME}-slave-ruby"
    spec: 
      output: 
        to: 
          kind: ImageStreamTag
          name: "${JENKINS_SERVICE_NAME}-slave-ruby:latest"
      runPolicy: Serial
      source: 
        contextDir: slave-ruby
        git: 
          ref: "${GITHUB_REF}"
          uri: "https://github.com/${GITHUB_ORG}/wendy-jenkins-s2i-configuration"
        type: Git
      strategy: 
        dockerStrategy: 
          noCache: true
        type: Docker
      triggers: 
        - 
          type: ImageChange
        - 
          type: ConfigChange
  - 
    apiVersion: v1
    kind: ImageStream
    metadata: 
      annotations: 
        slave-label: ruby-fhcap
      labels: 
        role: jenkins-slave
      name: "${JENKINS_SERVICE_NAME}-slave-ruby-fhcap"
  - 
    apiVersion: v1
    kind: BuildConfig
    metadata: 
      name: "${JENKINS_SERVICE_NAME}-slave-ruby-fhcap"
    spec: 
      output: 
        to: 
          kind: ImageStreamTag
          name: "${JENKINS_SERVICE_NAME}-slave-ruby-fhcap:latest"
      runPolicy: Serial
      source: 
        contextDir: slave-ruby-fhcap
        git: 
          ref: "${GITHUB_REF}"
          uri: "https://github.com/${GITHUB_ORG}/wendy-jenkins-s2i-configuration"
        type: Git
      strategy: 
        type: Docker
      triggers: 
        - 
          type: ImageChange
        - 
          type: ConfigChange
  -
    apiVersion: v1
    kind: "LimitRange"
    metadata:
      name: jenkins-resource-limits
    spec:
      limits:
        - type: Container
          defaultRequest:
            cpu: 1
            memory: 1Gi
parameters: 
  - 
    description: "The name of the OpenShift Service exposed for the Jenkins container."
    displayName: "Jenkins Service Name"
    name: JENKINS_SERVICE_NAME
    value: jenkins
  - 
    description: "The name of the github organization to reference in the configuration"
    displayName: "Github Organization"
    name: GITHUB_ORG
    value: feedhenry
  - 
    description: "The name of the repository branch to reference in the configuration"
    displayName: Branch
    name: GITHUB_REF
    value: master