#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

docker run --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'go version'

echo "SUCCESS!"
