#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

docker run ${IMAGE_NAME} oc
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'make --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'wget --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'zip --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'tar --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'java -version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'ant -version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'mvn --version'

echo "SUCCESS!"
