#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

# make sure jq & circleci-cli is available
docker run ${IMAGE_NAME} jq --version
docker run ${IMAGE_NAME} circleci --version

echo "SUCCESS!"
