#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

# make sure pip and boto are installed
# the default entrypoint for the image assumes if you supply more than
# one arg, you are trying to invoke the agent logic, so we have to
# override the entrypoing to run complicated commands for testing.
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'pip --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'python -c "import boto"'

echo "SUCCESS!"
