---
apiVersion: v1
kind: Template
labels:
  template: jenkins-build-wendy-template
message: A Jenkins build-config template
metadata:
  annotations:
    description: |-
        Jenkins build config template 
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jenkins-wendy
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${JENKINS_SERVICE_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${JENKINS_SERVICE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${JENKINS_SERVICE_NAME}:latest
    runPolicy: Serial
    source:
      dockerfile: |-
        FROM openshift/jenkins-2-rhel7
        USER example
      git:
        uri: https://github.com/${GITHUB_ORG}/wendy-jenkins-s2i-configuration.git
        ref: ${GITHUB_REF}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/openshift3/jenkins-2-rhel7:latest
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange

parameters:
- description: The name of the github organization to reference in the configuration
  displayName: Github Organization
  name: GITHUB_ORG
  value: feedhenry
- description: The name of the repository branch to reference in the configuration
  displayName: Branch
  name: GITHUB_REF
  value: master
- description: The name of the OpenShift Service exposed for the Jenkins container.
  displayName: Jenkins Service Name
  name: JENKINS_SERVICE_NAME
  value: jenkins
- description: The name of the service used for master/slave communication.
  displayName: Jenkins JNLP Service Name
  name: JNLP_SERVICE_NAME
  value: jenkins-jnlp
