#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

docker run ${IMAGE_NAME} oc
docker run --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'npm --version'
docker run --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'node --version'
docker run --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'openshift-template-tool version'
echo "SUCCESS!"
