#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

docker run --rm -t --entrypoint=/bin/bash ${IMAGE_NAME} -ic 'source /usr/local/bin/configure-slave && oc version'
docker run --rm -t --entrypoint=/bin/bash ${IMAGE_NAME} -ic 'source /usr/local/bin/configure-slave && git --version'
docker run --rm -t --entrypoint=/bin/bash ${IMAGE_NAME} -ic 'source /usr/local/bin/configure-slave && npm --version'
docker run --rm -t --entrypoint=/bin/bash ${IMAGE_NAME} -ic 'source /usr/local/bin/configure-slave && node --version'
docker run --rm -t --entrypoint=/bin/bash ${IMAGE_NAME} -ic 'source /usr/local/bin/configure-slave && openshift-template-tool version'

echo "SUCCESS!"
