#!/bin/bash -e
#
# Test the Jenkins image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

# make sure oc is installed
docker run ${IMAGE_NAME} oc
# make sure gem and ruby are available
# the default entrypoint for the image assumes if you supply more than
# one arg, you are trying to invoke the agent logic, so we have to
# override the entrypoing to run complicated commands for testing.
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'gem --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'ruby --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'fhcap --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'openssl version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'nova --version 2>&1 | grep 7.1.0'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'aws --version 2>&1 | grep 1.11.80'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'git --version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -ic 'foodcritic --version 2>&1 | grep 4.0.0'

echo "SUCCESS!"
